# Website's icon url.
favicon: /favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
#logo:
#  text: superAsir's Notes
logo: https://github.com/asirzhao/blog-image/raw/master/blog/other/profile.jpeg

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  Home: /
  Archives: /archives
#  Tags: /tags
  Categories: /categories
#  Lifestyle: /categories/LifeStyle
#  Music: /categories/Music
#  Technology: /categories/Technology
  About: /about

# Search plugin settings.
search:
  type: insight

# Share plugin settings.
share:
  type: addthis 
  install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a694d4d78479a8b

# Comment plugin settings.
comment:
  type: disqus
  shortname: supaerasir

# Other plugins and their settings.
plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/asirzhao
  Twitter:
    icon: fab fa-twitter
    url: https://twitter.com/asir_zhao
  Instagram:
    icon: fab fa-instagram
    url: https://www.instagram.com/zhaoyao0560/
  Weibo: 
    icon: fab fa-weibo
    url: https://weibo.com/2144484004/profile?topnav=1&wvr=6&is_all=1
  Best Fellow:
    icon: fas fa-user-astronaut
    url: https://www.unbelievable9.info/
  Little Bro:
    icon: fas fa-user-graduate
    url: https://rainfung.github.io/
#  Mail:
#    icon: fas fa-envelope
#    url: mailto:joeAsir0560@outlook.com
  
# Links at the bottom of the page.
footer_links:
    GitHub: https://github.com/asirzhao
    Twitter: https://twitter.com/asir_zhao
    Instagram: https://www.instagram.com/zhaoyao0560/
    Weibo: https://weibo.com/2144484004/profile?topnav=1&wvr=6&is_all=1

